const APP_KEY='cuadernoEF_v1';
const criteria=[
 ['1.1','CE1',5],['1.2','CE1',5],['1.3','CE1',4],['1.4','CE1',3],['1.5','CE1',3],['1.6','CE1',5],
 ['2.1','CE2',5],['2.2','CE2',6],['2.3','CE2',8],['2.4','CE2',6],
 ['3.1','CE3',7],['3.2','CE3',7],['3.3','CE3',6],
 ['4.1','CE4',6],['4.2','CE4',5],['4.3','CE4',4],
 ['5.1','CE5',5],['5.2','CE5',5],['5.3','CE5',5]
];
const ceWeights={CE1:25,CE2:25,CE3:20,CE4:15,CE5:15};
const ups=[
 ['UP1','Valoración de la condición física'],['UP2','Calentamiento'],['UP3','Capacidades físicas básicas'],['UP4','Bádminton'],['UP5','Coordinación y equilibrio'],['UP6','Salud'],['UP7','Habilidades gimnásticas'],['UP8','Combas'],['UP9','Minibásquet'],['UP10','Expresión corporal'],['UP11','Juegos y deportes alternativos'],['UP12','Juegos y deportes tradicionales'],['UP13','Senderismo y orientación']
];
const evidence={
'1.1':[['UP1','Revisión de portfolio','Pasaporte de condición física'],['UP3','Revisión de portfolio','Seguimiento y regulación de CFB'],['UP6','Presentación de producto','Producto aplicado sobre hábitos saludables']],
'1.2':[['UP2','Presentación de producto','Diseño y dirección de calentamiento'],['UP3','Prueba de ejecución','Reto de regulación del esfuerzo']],
'1.3':[['UP6','Prueba objetiva','Aplicación de hábitos saludables']],
'1.4':[['UP6','Prueba objetiva','Prevención y actuación ante situaciones de riesgo']],
'1.5':[['UP6','Presentación de producto','Análisis crítico de prácticas y hábitos']],
'1.6':[['UP1','Observación sistemática','Participación responsable y regulación del esfuerzo'],['UP3','Observación sistemática','Participación responsable y autorregulación']],
'2.1':[['UP11','Prueba de ejecución','Resolución autónoma de situaciones motrices']],
'2.2':[['UP4','Prueba de ejecución','Juego real/modificado de bádminton'],['UP9','Prueba de ejecución','Juego reducido 3×3 de minibásquet']],
'2.3':[['UP4','Prueba de ejecución','Juego real/modificado de bádminton'],['UP5','Prueba de ejecución','Circuito/reto coordinativo'],['UP7','Prueba de ejecución','Composición gimnástica'],['UP8','Presentación de producto','Secuencia cooperativa de combas'],['UP9','Prueba de ejecución','Juego reducido 3×3 de minibásquet'],['UP10','Presentación de producto','Creación y representación colectiva']],
'2.4':[['UP4','Prueba de ejecución','Aplicación de principios y reglas en bádminton'],['UP9','Prueba de ejecución','Aplicación de principios y reglas en minibásquet']],
'3.1':[['UP4','Observación sistemática','Autorregulación y participación en juego'],['UP9','Observación sistemática','Autorregulación en 3×3'],['UP11','Observación sistemática','Participación y autonomía'],['UP13','Observación sistemática','Autorregulación en entorno real']],
'3.2':[['UP7','Observación sistemática','Cooperación en composición gimnástica'],['UP10','Observación sistemática','Cooperación en creación colectiva'],['UP11','Observación sistemática','Cooperación en deportes alternativos'],['UP12','Observación sistemática','Cooperación en el proyecto ApS'],['UP13','Observación sistemática','Cooperación en orientación/senderismo']],
'3.3':[['UP4','Observación sistemática','Respeto y deportividad'],['UP7','Observación sistemática','Respeto y ayuda entre iguales'],['UP9','Observación sistemática','Deportividad e interacción'],['UP10','Observación sistemática','Respeto en creación colectiva'],['UP11','Observación sistemática','Respeto y convivencia']],
'4.1':[['UP10','Presentación de producto','Representación expresiva colectiva'],['UP12','Revisión de portfolio','Baúl de los juegos del instituto']],
'4.2':[['UP9','Diálogo/debate','Baloncesto, igualdad y referentes'],['UP12','Trabajo de investigación','Estereotipos y memoria lúdica']],
'4.3':[['UP10','Presentación de producto','Uso expresivo y comunicativo del cuerpo']],
'5.1':[['UP13','Prueba de ejecución','Recorrido/reto de orientación']],
'5.2':[['UP13','Observación sistemática','Seguridad y gestión del riesgo']],
'5.3':[['UP13','Revisión de portfolio','Uso responsable y sostenible del entorno']]
};
const compMatrix={
'1.5':['UP2'],'1.6':['UP2','UP6'],'2.1':['UP4'],'2.2':['UP11'],'3.1':['UP3','UP5','UP7','UP8'],'3.2':['UP2','UP3','UP4'],'3.3':['UP1','UP2','UP3'],'4.1':['UP8']
};
let state=load(); let currentView='inicio'; let deferredPrompt=null;
function defaultState(){return {groups:[],scores:{},qual:{},selectedGroup:null,selectedUP:'UP1'};}
function load(){try{return Object.assign(defaultState(),JSON.parse(localStorage.getItem(APP_KEY)||'{}'))}catch{return defaultState()}}
function save(){localStorage.setItem(APP_KEY,JSON.stringify(state));}
function id(){return Math.random().toString(36).slice(2,10)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function toast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),1800)}
function group(){return state.groups.find(g=>g.id===state.selectedGroup)||state.groups[0]||null}
function scoreKey(gid,sid,c,seq){return `${gid}|${sid}|${c}|${seq}`}
function qualKey(gid,sid,c,up){return `${gid}|${sid}|${c}|${up}`}
function criterionValue(gid,sid,c){const es=evidence[c]||[];let num=0,den=0;es.forEach((_,i)=>{const v=state.scores[scoreKey(gid,sid,c,i+1)];if(v!==undefined&&v!==null&&v!==''){num+=Number(v)*(i+1);den+=(i+1)}});return den?num/den:null}
function ceValue(gid,sid,ce){let num=0,den=0;criteria.filter(x=>x[1]===ce).forEach(([c,,w])=>{const v=criterionValue(gid,sid,c);if(v!==null){num+=v*w;den+=w}});return den?num/den:null}
function coverage(gid,sid){return criteria.reduce((a,[c,,w])=>a+(criterionValue(gid,sid,c)!==null?w:0),0)}
function finalGrade(gid,sid){let num=0,den=0;criteria.forEach(([c,,w])=>{const v=criterionValue(gid,sid,c);if(v!==null){num+=v*w;den+=w}});return den?num/den:null}
function render(){document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));const fn={inicio:viewInicio,evaluar:viewEvaluar,seguimiento:viewSeguimiento,resumen:viewResumen,ajustes:viewAjustes}[currentView];document.getElementById('app').innerHTML=fn();bind();}
function viewInicio(){const g=group(); const n=g?g.students.length:0;return `
<div class="card"><h2>Panel del curso</h2><div class="grid"><div class="metric"><span>Grupo</span><strong>${g?esc(g.name):'—'}</strong></div><div class="metric"><span>Alumnado</span><strong>${n}</strong></div><div class="metric"><span>UP actual</span><strong>${state.selectedUP}</strong></div><div class="metric"><span>Modelo</span><strong>● + ○</strong></div></div></div>
<div class="card"><h3>Acción rápida</h3>${g?`<div class="toolbar"><button class="btn" data-go="evaluar">Evaluar evidencias ●</button><button class="btn secondary" data-go="seguimiento">Registrar ○</button><button class="btn secondary" data-go="resumen">Ver progreso</button></div>`:`<div class="empty">Crea tu primer grupo en Ajustes para empezar.</div>`}</div>
<div class="card"><h3>Regla del cuaderno</h3><p>No acumula “notas de tareas”: acumula <b>evidencias sobre criterios</b>. Las ● califican mediante progreso por recencia; las ○ apoyan el seguimiento y la consistencia.</p></div>`}
function groupSelectors(){return `<div class="row"><div><label>Grupo</label><select id="groupSel">${state.groups.map(g=>`<option value="${g.id}" ${g.id===state.selectedGroup?'selected':''}>${esc(g.name)}</option>`).join('')}</select></div><div><label>Unidad</label><select id="upSel">${ups.map(([u,n])=>`<option value="${u}" ${u===state.selectedUP?'selected':''}>${u} · ${esc(n)}</option>`).join('')}</select></div></div>`}
function principalForUP(up){let arr=[];criteria.forEach(([c])=>(evidence[c]||[]).forEach((e,i)=>{if(e[0]===up)arr.push({c,seq:i+1,proc:e[1],desc:e[2]})}));return arr}
function viewEvaluar(){const g=group();if(!g)return `<div class="card empty">Primero crea un grupo en Ajustes.</div>`;const evs=principalForUP(state.selectedUP);return `${groupSelectors()}<div class="card"><h2>Evidencias principales ●</h2>${evs.length?`<label>Evidencia</label><select id="evSel">${evs.map((e,i)=>`<option value="${i}">${e.c} · ${esc(e.desc)}</option>`).join('')}</select><div id="evMeta" class="muted"></div><div id="studentScores"></div>`:`<div class="empty">No hay evidencias ● en esta UP.</div>`}</div>`}
function scoreListHTML(ev){const g=group();if(!g)return '';return g.students.map(s=>{const k=scoreKey(g.id,s.id,ev.c,ev.seq);const v=state.scores[k];return `<div class="student-row"><div><b>${esc(s.name)}</b><div class="tiny">Criterio ${ev.c}</div></div><div class="score-buttons">${[0,4,5,6,7,8,9,10].map(x=>`<button data-score="${x}" data-key="${k}" class="${String(v)===String(x)?'selected':''}">${x}</button>`).join('')}<button data-clear="${k}">×</button></div></div>`}).join('')}
function viewSeguimiento(){const g=group();if(!g)return `<div class="card empty">Primero crea un grupo en Ajustes.</div>`;let comps=[];Object.entries(compMatrix).forEach(([c,arr])=>arr.forEach(up=>{if(up===state.selectedUP)comps.push({c,up})}));return `${groupSelectors()}<div class="card"><h2>Seguimiento complementario ○</h2>${comps.length?`<label>Criterio</label><select id="compSel">${comps.map((e,i)=>`<option value="${i}">${e.c} · ${e.up}</option>`).join('')}</select><div id="qualList"></div>`:`<div class="empty">No hay evidencias ○ previstas en esta UP.</div>`}</div>`}
function qualListHTML(c,up){const g=group();return g.students.map(s=>{const k=qualKey(g.id,s.id,c,up),v=state.qual[k]||'';return `<div class="student-row"><div><b>${esc(s.name)}</b><div class="tiny">${c} · ${up}</div></div><select data-qual-key="${k}"><option value="">—</option>${['En proceso','Adecuado','Consolidado'].map(x=>`<option ${v===x?'selected':''}>${x}</option>`).join('')}</select></div>`}).join('')}
function viewResumen(){const g=group();if(!g)return `<div class="card empty">Primero crea un grupo en Ajustes.</div>`;return `${groupSelectors()}<div class="card"><h2>Resumen del grupo</h2><div class="table-wrap"><table><thead><tr><th>Alumno/a</th><th>Cobertura</th><th>CE1</th><th>CE2</th><th>CE3</th><th>CE4</th><th>CE5</th><th>Nota</th></tr></thead><tbody>${g.students.map(s=>{const cov=coverage(g.id,s.id),grade=finalGrade(g.id,s.id);return `<tr><td class="name">${esc(s.name)}</td><td>${cov.toFixed(0)}%</td>${['CE1','CE2','CE3','CE4','CE5'].map(ce=>{const v=ceValue(g.id,s.id,ce);return `<td>${v===null?'—':v.toFixed(2)}</td>`}).join('')}<td class="${grade===null?'':grade<5?'bad':grade<7?'warn':'ok'}"><b>${grade===null?'—':grade.toFixed(2)}</b></td></tr>`}).join('')}</tbody></table></div></div>
<div class="card"><h3>Detalle individual</h3><label>Alumno/a</label><select id="studentDetailSel">${g.students.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select><div id="studentDetail"></div></div>`}
function detailHTML(sid){const g=group();const s=g.students.find(x=>x.id===sid);if(!s)return '';return `<div class="table-wrap" style="margin-top:10px"><table><thead><tr><th>Criterio</th><th>Peso</th><th>Nivel actual</th></tr></thead><tbody>${criteria.map(([c,,w])=>{const v=criterionValue(g.id,s.id,c);return `<tr><td>${c}</td><td>${w}%</td><td>${v===null?'—':v.toFixed(2)}</td></tr>`}).join('')}</tbody></table></div>`}
function auditData(){const sums={};criteria.forEach(([c,,w])=>{const es=evidence[c]||[],n=es.length;es.forEach((e,i)=>{const share=w*(i+1)/(n*(n+1)/2);sums[e[1]]=(sums[e[1]]||0)+share})});return sums}
function viewAjustes(){const a=auditData();return `<div class="card"><h2>Grupos y alumnado</h2><div class="row"><input id="newGroup" placeholder="Ej. 1.º ESO A"><button class="btn" id="addGroup">Crear grupo</button></div>${state.groups.map(g=>`<div class="card" style="margin-top:10px"><div class="row"><div><b>${esc(g.name)}</b><div class="tiny">${g.students.length} alumnos</div></div><button class="btn small secondary" data-select-group="${g.id}">Usar</button><button class="btn small danger" data-delete-group="${g.id}">Borrar</button></div><div class="row" style="margin-top:8px"><textarea id="bulk-${g.id}" rows="3" placeholder="Pega un alumno por línea"></textarea><button class="btn small" data-add-students="${g.id}">Añadir</button></div></div>`).join('')}</div>
<div class="card"><h2>Auditoría 40 %</h2>${Object.entries(a).map(([p,v])=>`<div style="margin-bottom:9px"><div class="row"><span>${esc(p)}</span><b>${v.toFixed(2)}%</b></div><div class="progress"><span style="width:${Math.min(v,100)}%"></span></div></div>`).join('')}<p class="muted">Todos los procedimientos deben permanecer ≤ 40 %.</p></div>
<div class="card"><h2>Copias de seguridad</h2><div class="toolbar"><button class="btn" id="exportJson">Exportar copia JSON</button><label class="btn secondary" style="display:inline-block">Importar JSON<input type="file" id="importJson" accept="application/json" hidden></label><button class="btn secondary" id="exportCsv">Exportar resumen CSV</button></div><p class="muted">Los datos se guardan solo en este dispositivo/navegador. Haz copias periódicas.</p></div>`}
function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{currentView=b.dataset.go;render()});document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;render()});
 const gs=document.getElementById('groupSel');if(gs)gs.onchange=e=>{state.selectedGroup=e.target.value;save();render()};const us=document.getElementById('upSel');if(us)us.onchange=e=>{state.selectedUP=e.target.value;save();render()};
 if(currentView==='evaluar'){const evs=principalForUP(state.selectedUP), sel=document.getElementById('evSel'), meta=document.getElementById('evMeta'), box=document.getElementById('studentScores');const draw=()=>{const ev=evs[Number(sel.value)||0];meta.innerHTML=`<span class="pill main">● ${ev.c}</span> · ${esc(ev.proc)}<br>${esc(ev.desc)}`;box.innerHTML=scoreListHTML(ev);box.querySelectorAll('[data-score]').forEach(b=>b.onclick=()=>{state.scores[b.dataset.key]=Number(b.dataset.score);save();draw()});box.querySelectorAll('[data-clear]').forEach(b=>b.onclick=()=>{delete state.scores[b.dataset.clear];save();draw()})};if(sel){sel.onchange=draw;draw()}}
 if(currentView==='seguimiento'){let comps=[];Object.entries(compMatrix).forEach(([c,arr])=>arr.forEach(up=>{if(up===state.selectedUP)comps.push({c,up})}));const sel=document.getElementById('compSel'),box=document.getElementById('qualList');const draw=()=>{const ev=comps[Number(sel.value)||0];box.innerHTML=qualListHTML(ev.c,ev.up);box.querySelectorAll('[data-qual-key]').forEach(s=>s.onchange=()=>{if(s.value)state.qual[s.dataset.qualKey]=s.value;else delete state.qual[s.dataset.qualKey];save()})};if(sel){sel.onchange=draw;draw()}}
 if(currentView==='resumen'){const sd=document.getElementById('studentDetailSel'),box=document.getElementById('studentDetail');const draw=()=>box.innerHTML=detailHTML(sd.value);if(sd){sd.onchange=draw;draw()}}
 const ag=document.getElementById('addGroup');if(ag)ag.onclick=()=>{const name=document.getElementById('newGroup').value.trim();if(!name)return;const g={id:id(),name,students:[]};state.groups.push(g);state.selectedGroup=g.id;save();render();toast('Grupo creado')};
 document.querySelectorAll('[data-select-group]').forEach(b=>b.onclick=()=>{state.selectedGroup=b.dataset.selectGroup;save();render()});document.querySelectorAll('[data-delete-group]').forEach(b=>b.onclick=()=>{if(confirm('¿Borrar este grupo y sus datos?')){const gid=b.dataset.deleteGroup;state.groups=state.groups.filter(g=>g.id!==gid);Object.keys(state.scores).filter(k=>k.startsWith(gid+'|')).forEach(k=>delete state.scores[k]);Object.keys(state.qual).filter(k=>k.startsWith(gid+'|')).forEach(k=>delete state.qual[k]);state.selectedGroup=state.groups[0]?.id||null;save();render()}});
 document.querySelectorAll('[data-add-students]').forEach(b=>b.onclick=()=>{const g=state.groups.find(x=>x.id===b.dataset.addStudents);const ta=document.getElementById('bulk-'+g.id);ta.value.split(/\n+/).map(x=>x.trim()).filter(Boolean).forEach(name=>g.students.push({id:id(),name}));save();render();toast('Alumnado añadido')});
 const ej=document.getElementById('exportJson');if(ej)ej.onclick=()=>download('cuaderno-ef-backup.json',JSON.stringify(state,null,2),'application/json');const ij=document.getElementById('importJson');if(ij)ij.onchange=async e=>{try{state=JSON.parse(await e.target.files[0].text());save();render();toast('Copia importada')}catch{alert('Archivo no válido')}};const ec=document.getElementById('exportCsv');if(ec)ec.onclick=exportCSV;
}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function exportCSV(){const g=group();if(!g){alert('Selecciona un grupo');return}const head=['Alumno','Cobertura','CE1','CE2','CE3','CE4','CE5','Nota'];const rows=g.students.map(s=>[s.name,coverage(g.id,s.id),...['CE1','CE2','CE3','CE4','CE5'].map(ce=>ceValue(g.id,s.id,ce)?.toFixed(2)||''),finalGrade(g.id,s.id)?.toFixed(2)||'']);download(`resumen-${g.name}.csv`,[head,...rows].map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(';')).join('\n'),'text/csv;charset=utf-8')}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.getElementById('installBtn').classList.remove('hidden')});document.getElementById('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
render();
